version: '3'
networks:
  elastic:
    external: true
services:
    python:
        build: ./ci/python
        container_name: "python"
        restart: always
        networks:
            - elastic
    kibana:
        image: docker.elastic.co/kibana/kibana:8.11.1
        container_name: "kibana"
        ports:
            - 5601:5601
        networks:
            - elastic

    elasticsearch:
        build: ./ci/elasticsearch
        container_name: "elasticsearch"
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        networks:
            - elastic
        volumes:
            - ./ci/data/es/db:/usr/share/elasticsearch/data
            - ./ci/data/es/logs:/usr/share/elasticsearch/logs
            - ./ci/data/es/repo:/usr/share/elasticsearch/repo
        ports:
            - "9203:9200"
        expose:
            - "9203"